export const enum OrderStatus {
  PENDING = 'PENDING',

  WAITPAYMENT = 'WAITPAYMENT',

  WAITPAYCONFIRM = 'WAITPAYCONFIRM',

  WAITSHIP = 'WAITSHIP',

  DECLINED = 'DECLINED',

  SHIPPING = 'SHIPPING',

  COMPLETED = 'COMPLETED',

  RETURNSHIPPING = 'RETURNSHIPPING',

  RETURNED = 'RETURNED',

  CANCELLED = 'CANCELLED',
}
